

CREATE TABLE `car_biz_order_cancel_reason` (
  `reason_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) DEFAULT NULL COMMENT '订单ID',
  `should_deducted` decimal(5,1) DEFAULT NULL COMMENT '应扣金额',
  `fact_deducted` decimal(5,1) DEFAULT NULL COMMENT '实扣金额',
  `cancel_reason_id` int(11) DEFAULT NULL COMMENT '关联取消原因表',
  `memo` text,
  `update_date` timestamp NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_by` int(11) DEFAULT NULL,
  `create_by` int(11) DEFAULT NULL,
  `cancel_type` varchar(500) DEFAULT NULL,
  `cancel_status` int(11) DEFAULT NULL COMMENT '1:pc端提交，2：手机端提交，3：乘客端APP(超时)\r\n4：系统自动取消(日租/半日租乘客15分钟内未付定金)  ，5：无司机，系统自动取消',
  PRIMARY KEY (`reason_id`),
  KEY `FK_INDEX_ORDER_ID` (`order_id`),
  KEY `ind_create_date` (`create_date`),
  KEY `ind_create_by` (`create_by`)
) ENGINE=InnoDB AUTO_INCREMENT=906691749 DEFAULT CHARSET=utf8;

CREATE TABLE `car_fact_order_specified` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) DEFAULT '0',
  `order_no` varchar(255) DEFAULT '',
  `multy_order_id` int(11) DEFAULT '0',
  `multy_order_no` varchar(255) DEFAULT '',
  `customer_id` int(11) DEFAULT NULL,
  `specified_drivers` varchar(255) DEFAULT '' COMMENT '指定多个司机id',
  `is_other_drivers` int(11) DEFAULT '0',
  `service_type_id` int(11) DEFAULT '0',
  `type` int(11) DEFAULT '0',
  `status` int(11) DEFAULT '0',
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_date` timestamp NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `language_service` int(11) DEFAULT NULL COMMENT '是否接受语言服务（1：接受 | 2：不接受）',
  `department_id` int(11) DEFAULT '0' COMMENT '机构部门id',
  `extend_int_two` int(11) DEFAULT '0',
  `extend_int_three` int(11) DEFAULT '0',
  `extend_int_four` int(11) DEFAULT '0',
  `extend_char_one` char(1) DEFAULT '0',
  `extend_char_two` char(1) DEFAULT '0',
  `extend_vc_one` varchar(255) DEFAULT '',
  `extend_vc_two` varchar(100) DEFAULT '',
  `extend_vc_three` varchar(50) DEFAULT '',
  `order_address` text COMMENT '订单上下车长短地址，格式：{key:value}',
  PRIMARY KEY (`id`),
  KEY `ind_order_id` (`order_id`),
  KEY `ind_order_no` (`order_no`),
  KEY `ind_customer_id` (`customer_id`),
  KEY `ind_multy_id` (`multy_order_id`),
  KEY `ind_multy_no` (`multy_order_no`),
  KEY `ind_create_date` (`create_date`),
  KEY `idx_department_id` (`department_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1351446945 DEFAULT CHARSET=utf8;


CREATE TABLE `car_fact_order` (
  `order_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `order_no` varchar(20) DEFAULT NULL,
  `type` int(2) DEFAULT '1' COMMENT '订单类型(1:普通用户订单, 2:企业用户订单)',
  `push_driver_type` int(11) DEFAULT NULL COMMENT '订单指派司机类型 1 系统强派| 2 司机抢单| 3 后台人工指派',
  `order_type` int(11) DEFAULT NULL COMMENT '订单类型',
  `booking_user_id` int(11) DEFAULT NULL,
  `booking_date` timestamp NULL DEFAULT NULL COMMENT '预约上车时间',
  `rider_name` varchar(20) DEFAULT NULL COMMENT '乘车人姓名',
  `rider_phone` varchar(30) DEFAULT NULL COMMENT '乘车人手机号',
  `booking_start_addr` varchar(200) DEFAULT NULL COMMENT '预定上车地点',
  `booking_start_point` varchar(100) DEFAULT NULL COMMENT '预定上车坐标点',
  `booking_end_addr` varchar(200) DEFAULT NULL COMMENT '预定下车地点',
  `booking_end_point` varchar(200) DEFAULT NULL COMMENT '预定下车坐标点',
  `fact_start_addr` varchar(200) DEFAULT NULL COMMENT '实际上车地点',
  `fact_start_point` varchar(200) DEFAULT NULL COMMENT '实际上车坐标点',
  `fact_end_addr` varchar(200) DEFAULT NULL  COMMENT '实际下车地点',
  `fact_end_point` varchar(200) DEFAULT NULL COMMENT '实际下车坐标点',
  `city_id` int(11) DEFAULT NULL COMMENT '城市',
  `service_type_id` int(11) DEFAULT NULL COMMENT '订单服务类型',
  `car_group_id` int(11) DEFAULT NULL COMMENT '车组',
  `driver_id` int(11) DEFAULT NULL  COMMENT '司机id',
  `license_plates` varchar(10) DEFAULT NULL COMMENT '车牌',
  `airline_no` varchar(20) DEFAULT NULL COMMENT '航班号',
  `airline_status` varchar(2) DEFAULT NULL COMMENT '航班状态',
  `airline_plan_date` timestamp NULL DEFAULT NULL COMMENT '航班计划出发时间',
  `airline_arr_date` timestamp NULL DEFAULT NULL COMMENT '航班计划到达时间',
  `airline_dep_code` varchar(10) DEFAULT NULL COMMENT '航班出发地三字码',
  `airline_arr_code` varchar(10) DEFAULT NULL COMMENT '航班目的地三字码',
  `channels_num` varchar(20) DEFAULT NULL COMMENT '渠道号',
  `receive_SMS` int(10) DEFAULT NULL COMMENT '预订人是否接收短信 1 接收 2 不接受',
  `estimated_Amount` decimal(7,2) DEFAULT '0.00' COMMENT '预估金额',
  `airport_id` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `create_by` int(11) DEFAULT NULL,
  `update_by` int(11) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT NULL,
  `update_date` timestamp NULL DEFAULT NULL,
  `memo` text,
  `fact_date` timestamp NULL DEFAULT NULL COMMENT '实际上车时间',
  `booking_groupids` varchar(255) DEFAULT NULL COMMENT '预定车型(多个,分隔)',
  `fact_driver_id` int(11) DEFAULT NULL,
  `fact_end_date` timestamp NULL DEFAULT NULL COMMENT '实际下车时间',
  `imei` varchar(50) DEFAULT NULL,
  `version` varchar(20) DEFAULT NULL COMMENT '软件版本号',
  `mobel_version` varchar(200) DEFAULT NULL COMMENT '手机版本号',
  `sys_version` varchar(20) DEFAULT NULL COMMENT '手机的系统版本',
  `platform` varchar(20) DEFAULT NULL COMMENT '平台',
  `pay_flag` int(20) DEFAULT '0' COMMENT '谁付款(0:预订人 | 1:乘车人 | 2:门童代人叫车乘车人是自己且乘车人付款',
  `cancelorder_penalty` decimal(10,2) DEFAULT NULL COMMENT '取消订单时扣除的违约金,违约金金额可能扣除充值账户、也可能扣除赠送账户、也可能扣信用卡',
  `chartered_id` int(11) DEFAULT NULL COMMENT '日租半日租主表 订单号',
  `chartered_order_no` varchar(50) DEFAULT NULL COMMENT '日租半日租主表 订单编号',
  `is_order_others` int(11) DEFAULT '0' COMMENT '是否代人叫车，0:不是；1:是',
  `doorman_pay_method` int(11) DEFAULT NULL COMMENT '门童代人叫车乘车人是自己且乘车人付款时, 支付方式(1:系统支付 | 2:现金支付)',
  `selected_pay_flag` int(11) DEFAULT NULL COMMENT '代人叫车时预定人选择的谁付款(0:预订人 | 1:乘车人)',
  `business_id` int(11) DEFAULT NULL COMMENT '机构id',
  `go_home_status` int(5) DEFAULT '0' COMMENT '回家模式 1 开启 0 未开启',
  `auto_level_up` int(5) DEFAULT '0' COMMENT '车型自动升级 1 开启 0 未开启',
  `booking_driver_id` int(11) DEFAULT NULL COMMENT '乘客指定的司机id，0未指定司机；-1 指定多个司机(司机id在中间表）；司机id-指定1个司机',
  `is_other_drivers` int(11) DEFAULT NULL COMMENT '是否接受其它司机(1：接受 | 2：不接受)',
  `booking_current_addr` varchar(255) DEFAULT NULL COMMENT '预定人下单时地点',
  `booking_current_point` varchar(255) DEFAULT NULL COMMENT '预定人下单时坐标',
  `booking_user_phone` varchar(255) DEFAULT NULL COMMENT '预定人电话',
  `buyout_flag` int(11) DEFAULT '0' COMMENT '一口价标志位,0:不是一口价订单;1:是一口价订单',
  `buyout_price` decimal(10,2) DEFAULT '0.00' COMMENT '一口价价格，目前针对携程接送机一口价订单;生成帐单、结算时需要以此字段为准',
  `booking_id_number` varchar(18) DEFAULT NULL COMMENT '预订人身份证号',
  `estimated_id` varchar(11) DEFAULT NULL COMMENT '预估费用id',
  `agent_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`order_id`),
  KEY `ind_driver_id` (`driver_id`),
  KEY `ind_rider_phone` (`rider_phone`),
  KEY `ind_booking_userid` (`booking_user_id`),
  KEY `ind_business_id` (`business_id`),
  KEY `ind_create_date` (`create_date`),
  KEY `ind_booking_date` (`booking_date`),
  KEY `ind_update_date` (`update_date`),
  KEY `IDX_ORDER_CHAID` (`chartered_id`) USING BTREE,
  KEY `ind_chartered_order_no` (`chartered_order_no`(16)),
  KEY `ind_order_no` (`order_no`),
  KEY `index_b_t_s` (`booking_user_id`,`type`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=1552620931 DEFAULT CHARSET=utf8

####
    字段类型修改: int -> bigint
car_biz_order_cancel_reason: reason_id / order_id
car_fact_order_specified: id / order_id
car_fact_order: order_id

索引修改:
1. 增加
cancel_reason: create_date
car_fact_order: update_date / business_id
####